import { Alert, Button, Card, Form, Input, Select, Space, Table, Tag, Typography } from 'antd';
import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { listCapabilityUpdateRequests, listProjectCapabilities, reviewCapabilityUpdateRequest, submitCapabilityUpdateRequest } from '@/features/project/api/projectApi';
import type { CapabilityUpdateRequest } from '@/features/project/api/projectApi';
import type { ProjectCapability } from '@/shared/types/project';
import { PermissionGuard } from '@/shared/components/PermissionGuard';

export function CapabilityRequestPage() { const { projectId = '' } = useParams(); const [caps, setCaps] = useState<ProjectCapability[]>([]); const [items, setItems] = useState<CapabilityUpdateRequest[]>([]); const [error, setError] = useState(''); const refresh = useCallback(() => Promise.all([listProjectCapabilities(projectId), listCapabilityUpdateRequests(projectId)]).then(([c, r]) => { setCaps(c); setItems(r); }).catch(() => setError('能力更新请求加载失败')), [projectId]); useEffect(() => { void refresh(); }, [refresh]); const submit = (values: Record<string, string>) => submitCapabilityUpdateRequest(projectId, values.capabilityId, { proposedValue: values.proposedValue, reason: values.reason, evidenceReference: values.evidenceReference }).then(refresh).catch(() => setError('请求提交失败')); return <div><Typography.Title level={3}>Capability Update Requests</Typography.Title>{error ? <Alert type="error" message={error} closable onClose={() => setError('')} /> : null}<Card title="提交能力更新" style={{ marginBottom: 20 }}><Form layout="inline" onFinish={(values) => void submit(values)}><Form.Item name="capabilityId" rules={[{ required: true }]}><Select style={{ width: 220 }} placeholder="Capability" options={caps.filter((c) => !c.derived).map((c) => ({ value: c.capabilityId, label: `${c.code} · ${c.name}` }))} /></Form.Item><Form.Item name="proposedValue" initialValue="YES"><Select options={['YES', 'NO', 'UNKNOWN'].map((value) => ({ value }))} /></Form.Item><Form.Item name="reason" rules={[{ required: true }]}><Input placeholder="Reason" /></Form.Item><Form.Item name="evidenceReference"><Input placeholder="Evidence reference" /></Form.Item><Button type="primary" htmlType="submit">提交</Button></Form></Card><Table rowKey="id" dataSource={items} columns={[{ title: 'Capability', dataIndex: 'capabilityId' }, { title: 'Current → Proposed', render: (_: unknown, r: CapabilityUpdateRequest) => `${r.currentValue} → ${r.proposedValue}` }, { title: 'Reason', dataIndex: 'reason' }, { title: 'Status', dataIndex: 'status', render: (v: string) => <Tag>{v}</Tag> }, { title: '审核', render: (_: unknown, r: CapabilityUpdateRequest) => r.status === 'PENDING' ? <PermissionGuard permission="capability_request:review"><Space><Button onClick={() => void reviewCapabilityUpdateRequest(projectId, r.id, true).then(refresh)}>批准</Button><Button danger onClick={() => void reviewCapabilityUpdateRequest(projectId, r.id, false).then(refresh)}>拒绝</Button></Space></PermissionGuard> : null }]} /></div>; }
export default CapabilityRequestPage;
