import { Alert, Button, Form, Input, Space, Table, Tag, Typography } from 'antd';
import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { listTestCaseChangeRequests, reviewTestCaseChangeRequest, submitTestCaseChangeRequest } from '@/features/project/api/projectApi';
import type { TestCaseChangeRequest } from '@/features/project/api/projectApi';
import { PermissionGuard } from '@/shared/components/PermissionGuard';

export function TestCaseChangeRequestPage() { const { masterId = '' } = useParams(); const [items, setItems] = useState<TestCaseChangeRequest[]>([]); const [error, setError] = useState(''); const refresh = useCallback(() => listTestCaseChangeRequests(masterId).then(setItems).catch(() => setError('测试用例变更请求加载失败')), [masterId]); useEffect(() => { void refresh(); }, [refresh]); return <div><Typography.Title level={3}>Test Case Change Requests</Typography.Title>{error ? <Alert type="error" message={error} /> : null}<Form layout="inline" onFinish={(v) => void submitTestCaseChangeRequest(masterId, v).then(refresh).catch(() => setError('请求提交失败'))}><Form.Item name="sourceVersionId" rules={[{ required: true }]}><Input placeholder="Published source version UUID" /></Form.Item><Form.Item name="reason" rules={[{ required: true }]}><Input placeholder="Reason" /></Form.Item><Button type="primary" htmlType="submit">提交请求</Button></Form><Table style={{ marginTop: 20 }} rowKey="id" dataSource={items} columns={[{ title: 'Source version', dataIndex: 'sourceVersionId' }, { title: 'Reason', dataIndex: 'reason' }, { title: 'Status', dataIndex: 'status', render: (v: string) => <Tag>{v}</Tag> }, { title: 'Revision draft', dataIndex: 'revisionDraftVersionId' }, { title: '审核', render: (_: unknown, r: TestCaseChangeRequest) => r.status === 'PENDING' ? <PermissionGuard permission="change_request:review"><Space><Button onClick={() => void reviewTestCaseChangeRequest(masterId, r.id, true).then(refresh)}>批准</Button><Button danger onClick={() => void reviewTestCaseChangeRequest(masterId, r.id, false).then(refresh)}>拒绝</Button></Space></PermissionGuard> : null }]} /></div>; }
export default TestCaseChangeRequestPage;
