import { Alert, Button, Card, Form, Input, Modal, Select, Space, Table, Tag, Typography } from 'antd';
import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { listStandards } from '@/features/dictionary/api/standardApi';
import { addProjectTestCase, addRecommendation, assignProjectTestCase, createProject, downloadProjectExport, getProject, ignoreRecommendation, listGenerationRuns, listProjectCapabilities, listProjectTestPlan, listProjects, removeProjectTestCase, restoreProjectTestCase, runGeneration, updateProjectCapability } from '@/features/project/api/projectApi';
import { PermissionGuard } from '@/shared/components/PermissionGuard';
import type { Project, ProjectCapability, ProjectSummary, GenerationRun, ProjectTestCase } from '@/shared/types/project';
import type { StandardTaskType } from '@/shared/types/dictionary';

export function ProjectPage() {
  const [projects, setProjects] = useState<ProjectSummary[]>([]); const [selected, setSelected] = useState<Project>();
  const [standards, setStandards] = useState<StandardTaskType[]>([]); const [capabilities, setCapabilities] = useState<ProjectCapability[]>([]);
  const [runs, setRuns] = useState<GenerationRun[]>([]); const [testPlan, setTestPlan] = useState<ProjectTestCase[]>([]); const [createOpen, setCreateOpen] = useState(false); const [loading, setLoading] = useState(false);
  const refresh = async () => { setProjects(await listProjects()); };
  useEffect(() => { void Promise.all([refresh(), listStandards({ enabled: true }).then(setStandards)]); }, []);
  const openProject = async (id: string) => { setLoading(true); try { const project = await getProject(id); setSelected(project); const [caps, generationRuns, plan] = await Promise.all([listProjectCapabilities(id), listGenerationRuns(id), listProjectTestPlan(id)]); setCapabilities(caps); setRuns(generationRuns); setTestPlan(plan); } finally { setLoading(false); } };
  const generate = async (mode: 'FULL' | 'PROGRESSIVE_INITIAL') => { if (!selected) return; setLoading(true); try { const run = await runGeneration(selected.id, mode); setRuns((old) => [run, ...old.filter((item) => item.id !== run.id)]); } finally { setLoading(false); } };
  return <div>
    <Space style={{ width: '100%', justifyContent: 'space-between' }}><Typography.Title level={3}>项目管理</Typography.Title><Button type="primary" onClick={() => setCreateOpen(true)}>新建项目</Button></Space>
    <Table rowKey="id" loading={loading} dataSource={projects} columns={[{ title: '编号', dataIndex: 'projectNumber' }, { title: '项目', dataIndex: 'projectName' }, { title: '设备', dataIndex: 'deviceName' }, { title: '模式', dataIndex: 'generationMode' }, { title: '状态', dataIndex: 'status', render: (v: string) => <Tag>{v}</Tag> }, { title: '操作', render: (_: unknown, row: ProjectSummary) => <Button type="link" onClick={() => void openProject(row.id)}>打开</Button> }]} />
    {selected ? <Card title={`${selected.projectNumber} · ${selected.projectName}`} loading={loading} style={{ marginTop: 24 }} extra={<Space><PermissionGuard permission="export:project"><Button onClick={() => void downloadProjectExport(selected.id).then((blob) => { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${selected.projectNumber}-export.xlsx`; anchor.click(); URL.revokeObjectURL(url); })}>导出 Excel</Button></PermissionGuard><Button onClick={() => void generate('FULL')}>运行 FULL Generation</Button><Button onClick={() => void generate('PROGRESSIVE_INITIAL')}>运行 Progressive Initial</Button></Space>}>
      <Typography.Paragraph>设备：{selected.deviceName} | 状态：<Tag>{selected.status}</Tag> | 标准：{selected.standardTaskTypeIds.map((id) => standards.find((s) => s.id === id)?.name ?? id).join('、')}</Typography.Paragraph><Space style={{ marginBottom: 16 }}><Link to={`/projects/${selected.id}/custom-cases`}><Button>Custom Cases</Button></Link><Link to={`/projects/${selected.id}/capability-requests`}><Button>Capability Requests</Button></Link></Space>
      <Typography.Title level={5}>Project Capability</Typography.Title>
      <Table size="small" rowKey="capabilityId" pagination={false} dataSource={capabilities} columns={[{ title: '能力', render: (_: unknown, r: ProjectCapability) => `${r.code} · ${r.name}` }, { title: '值', dataIndex: 'value', render: (value: string, r: ProjectCapability) => <Select disabled={r.derived} value={value} options={['YES', 'NO', 'UNKNOWN'].map((v) => ({ value: v }))} onChange={(v) => void updateProjectCapability(selected.id, r.capabilityId, { value: v, source: 'COORDINATOR_INPUT' }).then(() => openProject(selected.id))} /> }, { title: '来源', dataIndex: 'source' }]} />
      <Typography.Title level={5}>Recommendations</Typography.Title>{runs.map((run) => <Card size="small" key={run.id} title={`${run.mode} · ${new Date(run.executedAt).toLocaleString()}`} style={{ marginBottom: 12 }}><Table size="small" rowKey="id" pagination={false} dataSource={run.recommendations} columns={[{ title: 'Master', dataIndex: 'caseCode' }, { title: '状态', dataIndex: 'status', render: (v: string) => <Tag>{v}</Tag> }, { title: 'Recommended Because', render: (_: unknown, r) => r.recommendedBecause.map((rule: { ruleCode: string; ruleName: string }) => <Tag key={rule.ruleCode}>{rule.ruleCode} {rule.ruleName}</Tag>) }, { title: '操作', render: (_: unknown, r) => r.status === 'NEW' ? <Space><Button size="small" onClick={() => void addRecommendation(selected.id, r.id).then(() => openProject(selected.id))}>Add</Button><Button size="small" onClick={() => void ignoreRecommendation(selected.id, r.id).then(() => openProject(selected.id))}>Ignore</Button></Space> : null }]} /></Card>)}</Card> : null}
      {selected ? <div><Typography.Title level={5}>Project Test Plan</Typography.Title><Space style={{ marginBottom: 8 }}><Input id="manual-master-id" placeholder="Master Test Case UUID" /><Button onClick={() => { const input = document.getElementById('manual-master-id') as HTMLInputElement; if (input.value) void addProjectTestCase(selected.id, input.value).then(() => openProject(selected.id)); }}>Manual Add</Button></Space><Table size="small" rowKey="id" pagination={false} dataSource={testPlan} columns={[{ title: 'Case', dataIndex: 'caseCode' }, { title: 'Version', render: (_: unknown, r: ProjectTestCase) => r.testCaseVersionId ?? 'CUSTOM' }, { title: '来源', dataIndex: 'sources', render: (v: string[]) => v.join(', ') }, { title: '状态', render: (_: unknown, r: ProjectTestCase) => r.removed ? <Tag>REMOVED</Tag> : <Tag color="green">ACTIVE</Tag> }, { title: '操作', render: (_: unknown, r: ProjectTestCase) => <Space>{r.removed ? <Button size="small" onClick={() => void restoreProjectTestCase(selected.id, r.id).then(() => openProject(selected.id))}>Restore</Button> : <Button size="small" onClick={() => void removeProjectTestCase(selected.id, r.id).then(() => openProject(selected.id))}>Remove</Button>}<Button size="small" onClick={() => { const userId = window.prompt('TESTER user UUID'); if (userId) void assignProjectTestCase(selected.id, r.id, userId).then(() => openProject(selected.id)); }}>Assign</Button>{r.masterTestCaseId ? <Link to={`/my-tests/${r.id}/version`}>Version</Link> : null}</Space> }]} /></div> : null}
    <CreateProjectModal open={createOpen} standards={standards} onClose={() => setCreateOpen(false)} onCreated={(project) => { setCreateOpen(false); void refresh().then(() => openProject(project.id)); }} />
  </div>;
}
function CreateProjectModal({ open, standards, onClose, onCreated }: { open: boolean; standards: StandardTaskType[]; onClose: () => void; onCreated: (project: Project) => void }) {
  const [form] = Form.useForm(); const [error, setError] = useState<string>();
  return <Modal open={open} title="新建项目" onCancel={onClose} onOk={() => void form.validateFields().then((values) => createProject(values).then(onCreated).catch(() => setError('创建项目失败')))}><Form form={form} layout="vertical"><Form.Item name="projectName" label="项目名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="deviceName" label="设备名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="generationMode" label="生成模式" initialValue="FULL"><Select options={['FULL', 'PROGRESSIVE'].map((v) => ({ value: v, label: v }))} /></Form.Item><Form.Item name="standardTaskTypeIds" label="Standard / Task Type" rules={[{ required: true }]}><Select mode="multiple" options={standards.map((s) => ({ value: s.id, label: `${s.code} · ${s.name}` }))} /></Form.Item></Form>{error ? <Alert type="error" message={error} /> : null}</Modal>;
}
export default ProjectPage;
