import { Alert, Button, Card, Checkbox, Input, List, Space, Spin, Tabs, Tag, Typography, Upload, message } from 'antd';
import { UploadOutlined } from '@ant-design/icons';
import { Background, Controls, MiniMap, ReactFlow, type Edge, type Node } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { executionApi, type Evidence, type ExecutionDetail, type Note, type ProjectLogicGraph } from '@/features/execution/api/executionApi';

export function ExecutionPage() {
  const { projectTestCaseId = '' } = useParams();
  const [detail, setDetail] = useState<ExecutionDetail>(); const [evidence, setEvidence] = useState<Evidence[]>([]); const [notes, setNotes] = useState<Note[]>([]); const [graph, setGraph] = useState<ProjectLogicGraph>(); const [selected, setSelected] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [noteBody, setNoteBody] = useState('');
  const reload = useCallback(() => Promise.all([executionApi.detail(projectTestCaseId), executionApi.evidence(projectTestCaseId), executionApi.notes(projectTestCaseId)]).then(([d, e, n]) => { setDetail(d); setEvidence(e); setNotes(n); return executionApi.graph(d.projectId); }).then(setGraph).catch(() => setError('执行数据加载失败')).finally(() => setLoading(false)), [projectTestCaseId]);
  useEffect(() => { if (projectTestCaseId) void reload(); }, [projectTestCaseId, reload]);
  const nodes = useMemo<Node[]>(() => graph?.nodes.map((n, i) => ({ id: n.projectTestCaseId, position: { x: (i % 3) * 260, y: Math.floor(i / 3) * 140 }, data: { label: <Space direction="vertical"><b>{n.caseCode}</b><span>{n.executionStatus} · {n.relationStatus}</span>{n.root ? <Tag color="blue">ROOT</Tag> : null}</Space> }, style: { border: n.relationStatus === 'FLOATING' ? '2px solid #faad14' : n.executionStatus === 'COMPLETED' ? '2px solid #52c41a' : '2px solid #1677ff', borderRadius: 8, padding: 10 } })) ?? [], [graph]);
  const edges = useMemo<Edge[]>(() => graph?.edges.map((e) => ({ id: e.id, source: e.sourceProjectTestCaseId, target: e.targetProjectTestCaseId, label: e.label, animated: e.sourceProjectTestCaseId === projectTestCaseId })) ?? [], [graph, projectTestCaseId]);
  if (loading) return <Spin />; if (error || !detail) return <Alert type="error" message={error ?? '执行数据不存在'} />;
  const start = async () => { await executionApi.start(projectTestCaseId); await reload(); }; const complete = async () => { try { await executionApi.complete(projectTestCaseId, selected); message.success('执行已完成'); await reload(); } catch { message.error('完成失败，请检查证据和 Decision Point 选择'); } }; const reopen = async () => { await executionApi.reopen(projectTestCaseId); await reload(); };
  const addNote = async () => { if (!noteBody.trim()) return; await executionApi.createNote(projectTestCaseId, noteBody); setNoteBody(''); await reload(); };
  return <div><Typography.Title level={3}>执行测试</Typography.Title><Space><Tag>{detail.executionStatus}</Tag><Tag>{detail.selectionMode}</Tag>{detail.evidenceRequired ? <Tag color="orange">Evidence Required</Tag> : null}{detail.executionStatus === 'NOT_STARTED' ? <Button type="primary" onClick={() => void start()}>开始执行</Button> : null}{detail.executionStatus === 'IN_PROGRESS' ? <Button type="primary" onClick={() => void complete()}>完成</Button> : null}{detail.executionStatus === 'COMPLETED' ? <Button onClick={() => void reopen()}>重新打开</Button> : null}</Space><Tabs items={[{ key: 'decision', label: 'Decision Points', children: <Card><Checkbox.Group value={selected} onChange={(v) => setSelected(v as string[])} disabled={detail.executionStatus !== 'IN_PROGRESS'} options={detail.decisionPoints.map((d) => ({ label: `${d.displayOrder}. ${d.name} (${d.transitionType ?? '—'})`, value: d.id }))} /></Card> }, { key: 'evidence', label: `Evidence (${evidence.length})`, children: <Card><Upload beforeUpload={(file) => { void executionApi.uploadEvidence(projectTestCaseId, file).then(() => reload()); return false; }} showUploadList={false}><Button icon={<UploadOutlined />}>上传 Evidence</Button></Upload><List dataSource={evidence} renderItem={(item) => <List.Item actions={[<Button type="link" onClick={() => void executionApi.downloadEvidence(projectTestCaseId, item.id, item.originalFilename)}>下载</Button>, <Button danger type="link" onClick={() => void executionApi.deleteEvidence(projectTestCaseId, item.id).then(() => reload())}>删除</Button>]}>{item.originalFilename} · {item.sha256.slice(0, 12)}</List.Item>} /></Card> }, { key: 'notes', label: `Notes (${notes.length})`, children: <Card><Space.Compact style={{ width: '100%' }}><Input value={noteBody} onChange={(e) => setNoteBody(e.target.value)} placeholder="记录执行 Note" /><Button onClick={() => void addNote()}>添加</Button></Space.Compact><List dataSource={notes} renderItem={(item) => <List.Item actions={item.editable ? [<Button danger type="link" onClick={() => void executionApi.deleteNote(projectTestCaseId, item.id).then(() => reload())}>删除</Button>] : []}><List.Item.Meta title={item.authorName} description={new Date(item.createdAt).toLocaleString()} />{item.body}</List.Item>} /></Card> }, { key: 'graph', label: 'Project Logic Graph', children: <div style={{ height: 520 }}><ReactFlow nodes={nodes} edges={edges} fitView><MiniMap /><Controls /><Background /></ReactFlow></div> }]} /></div>;
}
export default ExecutionPage;
