import { Alert, Button, Card, Descriptions, Space, Tag, Typography } from 'antd';
import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { getVersionAvailability, keepProjectTestCaseVersion, upgradeProjectTestCaseVersion } from '@/features/project/api/projectApi';
import type { VersionAvailability } from '@/features/project/api/projectApi';
import { PermissionGuard } from '@/shared/components/PermissionGuard';

export function VersionUpgradePage() { const { projectTestCaseId = '' } = useParams(); const [item, setItem] = useState<VersionAvailability>(); const [error, setError] = useState(''); const refresh = useCallback(() => getVersionAvailability(projectTestCaseId).then(setItem).catch(() => setError('版本状态加载失败')), [projectTestCaseId]); useEffect(() => { void refresh(); }, [refresh]); if (!item) return <div>{error ? <Alert type="error" message={error} /> : '加载中…'}</div>; return <div><Typography.Title level={3}>Version Upgrade</Typography.Title><Card><Descriptions column={1}><Descriptions.Item label="Bound version">{item.boundVersionId}</Descriptions.Item><Descriptions.Item label="Current Published">{item.currentPublishedVersionId ?? '—'}</Descriptions.Item><Descriptions.Item label="Status"><Tag>{item.newVersionAvailable ? 'NEW VERSION AVAILABLE' : 'UP TO DATE'}</Tag></Descriptions.Item><Descriptions.Item label="Changed fields">{item.diff.changedFields.join(', ') || '—'}</Descriptions.Item></Descriptions>{item.diff.warning ? <Alert style={{ marginTop: 16 }} type="warning" message={item.diff.warning} /> : null}<PermissionGuard permission="project:update"><Space style={{ marginTop: 20 }}><Button onClick={() => void keepProjectTestCaseVersion(projectTestCaseId).then(refresh)}>Keep old version</Button><Button type="primary" disabled={!item.newVersionAvailable || !item.diff.compatible} onClick={() => void upgradeProjectTestCaseVersion(projectTestCaseId).then(refresh)}>Upgrade same PTC</Button></Space></PermissionGuard></Card></div>; }
export default VersionUpgradePage;
