-- V001: base schema + search extension
-- Final Technical Review §35: pgcrypto is NOT a V1 required extension;
-- UUIDs are generated by the application (Java). Only pg_trgm is enabled.

CREATE SCHEMA IF NOT EXISTS casehub;

CREATE EXTENSION IF NOT EXISTS pg_trgm;
