spring:
  jpa:
    show-sql: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: lax
