import { Alert, Button, Card, Form, Input, Select, Space, Table, Typography } from 'antd';
import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { assignCustomTestCase, createCustomTestCase, listCustomTestCases, submitCustomTestCaseToLibrary, updateCustomTestCase } from '@/features/project/api/projectApi';
import type { CustomTestCase } from '@/features/project/api/projectApi';
import { PermissionGuard } from '@/shared/components/PermissionGuard';

export function CustomCasePage() {
  const { projectId = '' } = useParams();
  const [items, setItems] = useState<CustomTestCase[]>([]); const [error, setError] = useState('');
  const refresh = useCallback(() => listCustomTestCases(projectId).then(setItems).catch(() => setError('自定义测试用例加载失败')), [projectId]);
  useEffect(() => { void refresh(); }, [refresh]);
  const create = (values: Record<string, unknown>) => createCustomTestCase(projectId, { caseCode: String(values.caseCode), caseName: String(values.caseName), testPurpose: '', preconditions: '', selectionMode: String(values.selectionMode ?? 'SINGLE'), evidenceRequired: false, evidenceRequirement: '', remarkRequirement: '', steps: [{ sequenceNo: 1, title: '执行步骤', content: String(values.stepContent) }], decisionPoints: values.dpName ? [{ displayOrder: 1, name: String(values.dpName), description: 'Custom transition', transitionType: String(values.transitionType ?? 'PASS'), targetMasterTestCaseIds: [], targetCustomTestCaseIds: [] }] : [] }).then(refresh).catch(() => setError('自定义测试用例创建失败'));
  const edit = (item: CustomTestCase) => { const name = window.prompt('Case Name', item.caseName); if (!name?.trim()) return; void updateCustomTestCase(projectId, item.id, { caseCode: item.caseCode, caseName: name.trim(), testPurpose: item.testPurpose ?? '', preconditions: item.preconditions ?? '', selectionMode: item.selectionMode, evidenceRequired: item.evidenceRequired, evidenceRequirement: item.evidenceRequirement ?? '', remarkRequirement: item.remarkRequirement ?? '', steps: item.steps, decisionPoints: item.decisionPoints.map((point) => ({ displayOrder: point.displayOrder, name: point.name, description: point.description ?? '', transitionType: point.transitionType, targetMasterTestCaseIds: point.targetMasterTestCaseIds ?? point.targets?.flatMap((target) => target.masterTestCaseId ? [target.masterTestCaseId] : []) ?? [], targetCustomTestCaseIds: point.targetCustomTestCaseIds ?? point.targets?.flatMap((target) => target.customTestCaseId ? [target.customTestCaseId] : []) ?? [] })) }).then(refresh).catch(() => setError('自定义测试用例更新失败')); };
  const assign = (item: CustomTestCase) => { const userId = window.prompt('Assignee user UUID'); if (userId?.trim() && item.projectTestCaseId) void assignCustomTestCase(projectId, item.id, userId.trim()).catch(() => setError('分配失败')); };
  return <div><Typography.Title level={3}>Project Custom Test Cases</Typography.Title>{error ? <Alert type="error" message={error} closable onClose={() => setError('')} /> : null}<Card title="创建自定义用例（Tester 创建后自动加入自己的 PTC Assignee）" style={{ marginBottom: 20 }}><Form layout="inline" onFinish={(values) => void create(values)}><Form.Item name="caseCode" rules={[{ required: true }]}><Input placeholder="Case Code" /></Form.Item><Form.Item name="caseName" rules={[{ required: true }]}><Input placeholder="Case Name" /></Form.Item><Form.Item name="stepContent" rules={[{ required: true }]}><Input placeholder="Step content" /></Form.Item><Form.Item name="dpName"><Input placeholder="Decision Point（可选）" /></Form.Item><Form.Item name="transitionType" initialValue="PASS"><Select options={['PASS', 'FAIL', 'NEXT_CASE'].map((value) => ({ value }))} /></Form.Item><Form.Item name="selectionMode" initialValue="SINGLE"><Select options={['SINGLE', 'MULTIPLE'].map((value) => ({ value }))} /></Form.Item><Button type="primary" htmlType="submit">创建</Button></Form></Card><Table rowKey="id" dataSource={items} columns={[{ title: 'Code', dataIndex: 'caseCode' }, { title: 'Name', dataIndex: 'caseName' }, { title: 'Steps / DPs', render: (_: unknown, item: CustomTestCase) => `${item.steps.length} / ${item.decisionPoints.length}` }, { title: 'PTC', dataIndex: 'projectTestCaseId' }, { title: '操作', render: (_: unknown, item: CustomTestCase) => <Space><Button onClick={() => edit(item)}>Edit</Button><PermissionGuard permission="project:update"><Button onClick={() => assign(item)}>Assignee</Button></PermissionGuard><Button onClick={() => void submitCustomTestCaseToLibrary(projectId, item.id).then(refresh).catch(() => setError('提交到测试库失败'))}>提交到测试库</Button></Space> }]} /></div>;
}
export default CustomCasePage;
